FROM eclipsecbi/centos:7

{{> Dockerfile.agentSetup }}

# Required for python36u
RUN yum install -y yum-utils && \
  yum install -y https://centos7.iuscommunity.org/ius-release.rpm

RUN yum update -y \
  && yum install -y \
  autoconf \
  automake \
  boost-test \
  blas \
  blas-devel \
  cmake \
  cppcheck \
  createrepo \
  doxygen \
  e2fsprogs-devel \
  gcc \
  gcc-c++ \
  git \
  gtk3 \
  ImageMagick \
  ImageMagick-devel \
  lapack \
  lapack-devel \
  libclang \
  libgtk-vnc-2.0-0 \
  libtool \
  libXtst \
  mailx \
  make \
  makeinfo \
  mariadb-libs \
  metacity \
  mutter \
  net-snmp-devel.x86_64 \
  okular \
  java-1.8.0-openjdk-devel \
  openssl-devel.x86_64 \
  patch \
  perl \
  perl-LDAP \
  python-gtk-vnc \
  python36u\
  rpm-build \
  strace \
  subversion \
  sysstat \
  tcl \
  tcpdump \
  tcsh \
  telnet \
  texlive \
  texlive-latex \
  texlive-tex4ht \
  tigervnc \
  tigervnc-server \
  tk \
  unrar \
  unzip \
  vino \
  webkitgtk \
  webkitgtk3 \
  wget \
  xmlstarlet \
  xorg-x11-apps.x86_64 \
  xorg-x11-drv-dummy.x86_64 \
  xorg-x11-drv-evdev.x86_64 \
  xorg-x11-drv-fbdev.x86_64 \
  xorg-x11-drv-keyboard.x86_64 \
  xorg-x11-drv-mouse.x86_64 \
  xorg-x11-drv-synaptics.x86_64 \
  xorg-x11-drv-vmmouse.x86_64 \
  xorg-x11-drv-void.x86_64 \
  xorg-x11-server-Xvfb.x86_64 \
  xterm \
  zip \
  zsh \
  && yum clean all

RUN ln -s /usr/bin/git /usr/local/bin/git \
  && ln -s /bin/bash /usr/local/bin/hipp_shell

ENV DISPLAY :0

RUN mkdir -p ${HOME}/.vnc && chmod -R 775 ${HOME} \
  && echo "123456" | vncpasswd -f > ${HOME}/.vnc/passwd \
  && chmod 600 ${HOME}/.vnc/passwd

# Create a custom vnc xstartup file
COPY scripts/xstartup_mutter.sh ${HOME}/.vnc/xstartup.sh
RUN chmod 755 ${HOME}/.vnc/xstartup.sh

# explicitly set locale
ENV LANG=en_US.UTF-8

USER 10001